---
- name: Update hosts file
  hosts: all
  
  tasks:
    - name: Update hosts file
      block:
        - name: Update hosts file on rhel hosts
          block:
            - name: Update hosts file on rhel hosts
              ansible.builtin.lineinfile:
                path: /etc/hosts
                line: "{{ item }}"
              loop: "{{ lookup('file', 'hosts_file.txt').splitlines() }}"
          when: ansible_facts['os_family'] == "RedHat"
        
        # - name: Update hosts file on windows hosts
        #   block:
        #     - name: Update hosts file on windows hosts
        #       ansible.windows.win_lineinfile:
        #         path: C:\Windows\System32\drivers\etc\hosts
        #         line: "{{ item }}"
        #       loop: "{{ lookup('file', 'hosts_file.txt').splitlines() }}"
        #   when: ansible_facts['os_family'] == "Windows"
